### PR TITLE
Add WebPubSub to bundles.

### PR DESCRIPTION
**Pull request by JialinXin**

### CODE REVIEW

**Comment by JialinXin** [comment]
@soninaren, @fabiocav, @paulbatum Can you help review? Thanks!

**Comment by paulbatum** [comment]
@JialinXin What does the GA timeline for these packages look like? The reason I ask is that we will need to GA the 3.0 bundle later this calendar year and we won't be able to have any preview packages at that point. I also noticed that you have a transitive dependency on Azure.Core.Experimental and I assume that will change prior to GA of the nuget package?

**Comment by JialinXin** [comment]
Thank you @paulbatum for the response. Our service GA is targeting September ~ October this year. We'd like to have the bundle integration earlier, because we'd like to have some docs and samples to convenient customers using Azure Functions as well as Static Web App which is highly rely on the bundle integration. 

How do you find the transitive dependency on `Azure.Core.Experimental`. I didn't notice this and not aware of it's releasing timeline.

Should I add into v2 for some early release?

**Comment by paulbatum** [comment]
Well, see the dependencies section here:
https://www.nuget.org/packages/Azure.Messaging.WebPubSub/

**Comment by JialinXin** [comment]
@vicancy to help check WebPubSub package status.

**Comment by vicancy** [comment]
Hi @KrzysztofCwalina `Azure.Messaging.WebPubSub` depends on a preview package `Azure.Core.Experimental`, do you know the timeline for its GA?

**Comment by KrzysztofCwalina** [comment]
@vicancy, we will move all the dependency types from Experimental to Azure.Core before WPS GA.

**Comment by JialinXin** [comment]
Thank @KrzysztofCwalina for the clarify.

@paulbatum Looks we will have another PR before GA to upgrade to release version. So can we merge this PR or wait until then?
And shall we also add to v2 for this package? Is there any release plan for v2 recently?

**Comment by paulbatum** [comment]
If you're asking about the 2.x bundle - no, this package should not be added to it because the 2.x bundle is GA.

@fabiocav what do you think? This seems OK to me, because if we decide to GA the 3.x bundle before the WPS nuget is GA, we can simply move it into the 4.x preview bundle. Any customer using WPS from a bundle would simply update their host.json to use the 4.x preview instead of the 3.x preview.

**Comment by JialinXin** [comment]
Hi, so can we make it merged? And do we have an estimation for the 3.0 release?

**Comment by JialinXin** [comment]
Hi @paulbatum, @fabiocav, is there any update? Anything we should do to make this PR merge?

**Comment by paulbatum** [comment]
Hi @JialinXin there is not much more I can do at this point. I sent a note to @fabiocav about this but it doesn't look like he got a chance to take a look and he is now OOF for a few weeks.

**Comment by JialinXin** [comment]
move to v3-preview with #103 as in preview stage.

**Pull request closed without merging**
