### PR TITLE
[4.x] Add SQL Bindings

### PR DESCRIPTION
**Pull request by Charles-Gagnon**

### CODE REVIEW

**Comment by Charles-Gagnon** [comment]
@soninaren 

1. I can't seem to build the bundle locally anymore (both here and in the 4.x-preview branch). I get this error : 

`Unhandled exception. System.IO.IOException: The file 'C:\src\azure-functions-extension-bundles\bin\NetCoreApp3_win_x8
6\bin_v3\win-x86\System.Configuration.ConfigurationManager.dll' already exists.`

Which seems related to the changes you made a while back to fix the dependency issue. Do you know anything about this or how to fix it?

2. I noticed that this branch is currently copying over the ConfigurationManager DLL (which is good)

https://github.com/Azure/azure-functions-extension-bundles/blob/v4.x/build/BuildSteps.cs#L191

But it's not copying over the Permissions DLL the 4.x-preview branch is. This wasn't something we needed so should be fine for our case, but just wanted to make sure that was expected.

**Comment by soninaren** [comment]
Closing the PR and creating a new one to resolve the permissions issue

**Comment by soninaren** [comment]
@Charles-Gagnon, you need to open a PR from a branch on the repo. As PR from fork will fail as it would not have permissions.

**Comment by soninaren** [comment]
Closed in favor of https://github.com/Azure/azure-functions-extension-bundles/pull/250

**Pull request closed without merging**
