### PR TITLE
Add DF MSSQL backend to V3

### PR DESCRIPTION
**Pull request by davidmrdavid**
As in title. In preparation for GA.

### CODE REVIEW

**Comment by davidmrdavid** [comment]
@soninaren: should we be adding this to V4 bundles as well, or can we expect that all extension in V3 will automagically be included in V4 once it GAs?

**Comment by davidmrdavid** [comment]
Seems the CI is failing because the MSSQL RC on Nuget is flagged as pre-release.

**Comment by cgillum** [comment]
> @soninaren: should we be adding this to V4 bundles as well, or can we expect that all extension in V3 will automagically be included in V4 once it GAs?

MSSQL was already included in the V4 bundles. In a [previous PR](https://github.com/Azure/azure-functions-extension-bundles/pull/162), I also incremented the major version to point to 1.

**Comment by soninaren** [comment]
> ld we be adding this to V4 bundles as well, or can we expect that all extension in V3 will automagically be included in V4 once it GAs?

We don't really have a branch for v4 bundle yet. Extension in v4.x branch when created would be a combination of extensions from v4.x-preview branch that have GA'd and extensions from v3.x branch. I don't think there are any action items for bundle v4 at the moment.

**Comment by fabiocav** [comment]
@davidmrdavid closing this PR as it is stale. Please reopen if still relevant.

**Pull request closed without merging**
