### PR TITLE
Add signalrtrigger to SignalRService (v2.x)

### PR DESCRIPTION
**Pull request by zackliu**
Add signalrtrigger to SignalRService

### CODE REVIEW

**Comment by zackliu** [comment]
@anthonychu  Could you please help to have a look.

**Comment by zackliu** [comment]
@soninaren Could you take a look?

**Comment by anthonychu** [comment]
I’m away this week. I haven’t had a chance to look at how the trigger is implemented. If it’s using the admin WebHooks like the event grid one, there’s a potential issue when used in a function app in azure static web apps. Those apps don’t have a storage account and don’t have function/host key secret storage needed to support the webhooks. I’d like to understand this more before adding, as it could break those apps. The event grid one fails even if the customer is not using the trigger.

**Comment by zackliu** [comment]
@anthonychu  Yeah, it uses webhook provider as seems there's no other provider in Function that we can leverage to generate a url to listen to.

**Comment by zackliu** [comment]
@anthonychu Updated binding version that supports Static Web Apps

**Comment by anthonychu** [comment]
This looks good. @gzuber please include in next release. Thanks!

**Pull request merged**
